---

hostname: "leaf-4"
lo_ip: "10.10.10.4/32"
bgp_asn: '65103'
bgp_routerid: '10.10.10.4'
interfaces:
  swp5:
    id: 'swp5' 
    ip: '10.10.0.12/31'
    desc: 'Leaf4-Spine1'
  swp6:
    id: 'swp6'
    ip: '10.10.0.14/31'
    desc: 'Leaf4-Spine2'