---

hostname: "leaf3"
lo_ip: "10.10.10.3/32"
bgp_asn: '65102'
bgp_routerid: '10.10.10.3'
interfaces:
  swp3:
    id: 'swp3' 
    ip: '10.10.0.8/31'
    desc: 'Leaf3-Spine1'
  swp4:
    id: 'swp4'
    ip: '10.10.0.10/31'
    desc: 'Leaf3-Spine2'