---

hostname: "leaf2"
lo_ip: "10.10.10.2/32"
bgp_asn: '65102'
bgp_routerid: '10.10.10.2'
interfaces:
  - id: 'lo' 
    ip: '10.10.10.2/32'
    type: loopback
    desc: 'Router Loopback'
neighbors:
  - name: swp2
  - name: swp6