---

    hostname: "spine1"
    lo_ip: "10.10.20.1/32"
    bgp_asn: '65201'
    bgp_routerid: '10.10.20.1'
    interfaces:
      swp2:
        id: 'swp2' 
        ip: '10.10.0.3/31'
        desc: 'Leaf2-Spine1'
      swp3:
        id: 'swp3'
        ip: '10.10.0.7/31'
        desc: 'Leaf2-Spine2'
      swp4:
        id: 'swp4'
        ip: '10.10.0.11/31'
        desc: 'Spine2-Leaf3'
      swp6:
        id: 'swp6'
        ip: '10.10.0.15/31'
        desc: 'Spine2-Leaf4'