---

    hostname: "spine1"
    lo_ip: "10.10.20.1/32"
    bgp_asn: '65201'
    bgp_routerid: '10.10.20.1'
    interfaces:
      swp1:
        id: 'swp1' 
        ip: '10.10.0.1/31'
        desc: 'Spine1-Leaf1'
      swp2:
        id: 'swp2'
        ip: '10.10.0.5/31'
        desc: 'Spine1-Leaf2'
      swp3:
        id: 'swp3'
        ip: '10.10.0.9/31'
        desc: 'Spine1-Leaf3'
      swp5:
        id: 'swp5'
        ip: '10.10.0.13/31'
        desc: 'Spine1-Leaf4'