---

hostname: "spine2"
lo_ip: "10.10.20.2/32"
bgp_asn: '65202'
bgp_routerid: '10.10.20.2'
interfaces:
  - id: 'lo' 
    ip: '10.10.20.2/32'
    type: loopback
    desc: 'Router Loopback'
neighbors:
  - name: swp5
  - name: swp6
  - name: swp7
  - name: swp8