---

hostname: "spine1"
lo_ip: "10.10.20.1/32"
bgp_asn: '65201'
bgp_routerid: '10.10.20.1'
interfaces:
  - id: 'lo' 
    ip: '10.10.20.1/32'
    type: loopback
    desc: 'Router Loopback'
neighbors:
  - name: swp1
  - name: swp2
  - name: swp3
  - name: swp4