---

version: "3.7"
services:
  gnmic:
    image: ghcr.io/openconfig/gnmic:latest
    container_name: gnmic
    volumes:
      - ./gnmic.yaml:/app/gnmic.yaml
    command: "subscribe --config /app/gnmic.yaml"
    ports:
      - 9804:9804
