---

hostname: "leaf4"
lo_ip: "10.10.10.4/32"
mgmt_ip: "192.168.200.14"
bgp_asn: '65104'
bgp_routerid: '10.10.10.4'
interfaces:
  - id: 'lo' 
    ip: '10.10.10.4/32'
    type: loopback
    desc: 'Router Loopback'
neighbors:
  - name: swp2
  - name: swp4
