vlans:
  - id: '100'
    vni: '100'
  - id: '200'
    vni: '200' 
  - id: '300'
    vni: '300'
  - id: '400'
    vni: '400'
  - id: '500'
    vni: '500'
  - id: '600'
    vni: '600'
  - id: '700'
    vni: '700'
  - id: '800'
    vni: '800'
  - id: '900'
    vni: '900'
  - id: '1000'
    vni: '1000'
  - id: '1100'
    vni: '1100'