---

- name: NVUE API
  hosts: leafs:spines
  gather_facts: false
  remote_user: cumulus
  connection: ansible.netcommon.httpapi

  tasks:
    - name: Create new revision
      nvidia.nvue.config:
        state: new
      register: revision

    - name: Dump revision
      ansible.builtin.debug:
        msg: '{{ revision.revid }}'

    - name: Set interface
      nvidia.nvue.interface:
        state: merged
        revid: '{{ revision.revid }}'
        data:
          - id: eth0
            description: "mgmt interfacedddd"
      register: interface

    - name: Dump previous output
      ansible.builtin.debug:
        msg: '{{ interface }}'

    - name: Apply new revision
      nvidia.nvue.config:
        state: apply
        revid: '{{ revision.revid }}'
        force: true
        wait: 10
      register: revision
