---

- name: NVUE API
  hosts: spine1
  gather_facts: false
  connection: ansible.netcommon.httpapi


  tasks:
  - name: List all interfaces
    nvidia.nvue.interface:
      interfaceid: "swp1"
      state: gathered
    register: interfaces



  - name: show
    ansible.builtin.debug:
      msg:
      - "{{ interfaces }}"

  
