---

  - name: NVUE API
    hosts: leafs:spines
    gather_facts: false
    remote_user: cumulus

    tasks:

      - name: Configure interfaces
        nvidia.nvue.command:
          template: |
            {% for i in interfaces %}
            set interface {{ interfaces[i].id }} ip address {{ interfaces[i].ip }}
            {% endfor %}
          apply: true
          assume_yes: true

