name: VLAN CI/CD

on:
  pull_request:
    paths:
      - 'inventory/interpod/group_vars/leafs/vlans/vlans.yaml'

  push:
    branches: [ main ]
    paths:
      - 'inventory/interpod/group_vars/leafs/vlans/vlans.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_KEY }}

      - name: Run VLAN playbook on automation server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@worker07.air.nvidia.com -p25845 \
            "cd /etc/ansible && ansible-playbook -i inventory/interpod playbooks/deploy_vlans.yaml"